# Generated by Django 3.2.4 on 2021-07-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnicornLog_REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Month, day, Year'),
        ),
    ]
