# Generated by Django 3.2.4 on 2021-07-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnicornLog_REST', '0002_alter_sighting_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'verbose_name_plural': 'Sightings'},
        ),
        migrations.AlterModelOptions(
            name='unicorn',
            options={'verbose_name_plural': 'Unicorns'},
        ),
    ]
